---
title: "温州 04 - 13 就业率分析"
author: "Dai Yichao (IVAN)"
date: "9/25/2020"
output: html_document
---

### Package needed: 

```{r, cache=TRUE}
options(warn = -1)
suppressMessages(library(ggplot2))
suppressMessages(library(Hmisc))
suppressMessages(library(dplyr))
suppressMessages(library(readxl))
suppressMessages(library(gridExtra))
suppressMessages(library(plotly))
library(statsr)
library(scales)
library(openxlsx)
library(ggstatsplot)
library(tidyr)
options(warn = 0)
```

---

需要的行列：地区代码，市，行业代码，全部从业人。

```{r}
dat2004 = read.csv('2004准确数据库.csv')
dat2005 = mdb.get('2005年企业数据库.mdb')
dat2006 = mdb.get('2006年企业数据库.mdb')
dat2007 = mdb.get('2007年中国工业企业数据库.mdb')
dat2008 = read.csv('中国工业企业数据库2008.csv')
dat2009 = mdb.get('2009年工业企业数据库.mdb')
dat2010 = mdb.get('2010年中国工业企业数据库.mdb')
dat2011 = mdb.get('2011年中国工业企业数据库.mdb')
dat2012 = mdb.get('2012年中国工业企业数据库.mdb')
dat2013 = read.csv('2013数据库.csv')
```

---

### 行政区号划分

```{r}
dt2004 = dat2004
dt2005 = dat2005
dt2006 = dat2006
dt2007 = dat2007
dt2008 = dat2008
dt2009 = dat2009
dt2010 = dat2010
dt2011 = dat2011
dt2012 = dat2012
dt2013 = dat2013


dt2004$地址代码 =       substr(dt2004$地址代码,1,5)
dt2004$地址代码 = as.numeric(dt2004$地址代码)
dt2004$地址代码 = 1000 * dt2004$地址代码 
dt2004$地址代码 = as.character(dt2004$地址代码)
dt2004$地址代码 =       substr(dt2004$地址代码,1,4)
dt2004 = as.data.frame(dt2004)
dt2004$地址代码 = as.character(dt2004$地址代码)


dt2005$行政区代码 =     substr(dt2005$行政区代码,1,4)
dt2006$行政区码 =       substr(dt2006$行政区码,1,4)
dt2007$行政区划代码 =   substr(dt2007$行政区划代码,1,4)
dt2008$行政区划代码 =   substr(dt2008$行政区划代码,1,4)
dt2009$行政区别 =       substr(dt2009$行政区别,1,4)
dt2010$行政区划代码 =   substr(dt2010$行政区划代码,1,4)
dt2010$行政区划代码 = as.character(dt2010$行政区划代码)
dt2011$行政区划代码 =   substr(dt2011$行政区划代码,1,4)
dt2012$X.行政区划代码 = substr(dt2012$X.行政区划代码,1,4)
dt2013$X.行政区划代码 = substr(dt2013$X.行政区划代码,1,4)



```

---

### 提取需要的变量

需要的行列：地区代码，市，行业代码，全部从业人。

```{r}

dt2004 = dt2004[dt2004$地址代码 == 3303,c('行业类别','全部从业人')]
dt2005 = dt2005[dt2005$行政区代码 == '3303', c('行业代码','从业人员总')]
dt2006 = dt2006[dt2006$行政区码 == '3303', c('行业代码','从业人员')]
dt2007 = dt2007[dt2007$行政区划代码 == '3303', c('行业代码','年末从业人员合计.总计')]
dt2008 = dt2008[dt2008$行政区划代码 == '3303', c('行业代码','全部从业人员年平均人数')]
dt2009 = dt2009[dt2009$行政区别 == '3303', c('行业代码','全部从业人员年平均人数')]
dt2010 = dt2010[dt2010$行政区划代码 == '3303', c('行业代码','年末从业人员合计.总计')]
dt2011 = dt2011[dt2011$行政区划代码 == '3303', c('行业代码','从业人数')]
dt2012 = dt2012[dt2012$X.行政区划代码 == '3303', c('行业代码','X.从业人数')]
dt2013 = dt2013[dt2013$X.行政区划代码 == '3303', c('行业代码','X.从业人数')]
```


### Same Col Names:

```{r}
colnames(dt2004) = c('行业代码','从业人数2004')
colnames(dt2005) = c('行业代码','从业人数2005')
colnames(dt2006) = c('行业代码','从业人数2006')
colnames(dt2007) = c('行业代码','从业人数2007')
colnames(dt2008) = c('行业代码','从业人数2008')
colnames(dt2009) = c('行业代码','从业人数2009')
colnames(dt2010) = c('行业代码','从业人数2010')
colnames(dt2011) = c('行业代码','从业人数2011')
colnames(dt2012) = c('行业代码','从业人数2012')
colnames(dt2013) = c('行业代码','从业人数2013')
dt2006$`从业人数2006` = as.numeric(as.character(dt2006$`从业人数2006`))
dt2007$`从业人数2007` = as.numeric(as.character(dt2007$`从业人数2007`))


dt2004$cou04 = 1
dt2005$cou05 = 1
dt2006$cou06 = 1
dt2007$cou07 = 1
dt2008$cou08 = 1
dt2009$cou09 = 1
dt2010$cou10 = 1
dt2011$cou11 = 1
dt2012$cou12 = 1
dt2013$cou13 = 1

```

### Group by 行业

```{r}
dt2004 = dt2004 %>% group_by(行业代码) %>% summarise_all(sum, na.rm = TRUE) %>% arrange(desc(行业代码))
dt2005 = dt2005 %>% group_by(行业代码) %>% summarise_all(sum, na.rm = TRUE) %>% arrange(desc(行业代码))
dt2006 = dt2006 %>% group_by(行业代码) %>% summarise_all(sum, na.rm = TRUE) %>% arrange(desc(行业代码))
dt2007 = dt2007 %>% group_by(行业代码) %>% summarise_all(sum, na.rm = TRUE) %>% arrange(desc(行业代码))
dt2008 = dt2008 %>% group_by(行业代码) %>% summarise_all(sum, na.rm = TRUE) %>% arrange(desc(行业代码))
dt2009 = dt2009 %>% group_by(行业代码) %>% summarise_all(sum, na.rm = TRUE) %>% arrange(desc(行业代码))
dt2010 = dt2010 %>% group_by(行业代码) %>% summarise_all(sum, na.rm = TRUE) %>% arrange(desc(行业代码))
dt2011 = dt2011 %>% group_by(行业代码) %>% summarise_all(sum, na.rm = TRUE) %>% arrange(desc(行业代码))
dt2012 = dt2012 %>% group_by(行业代码) %>% summarise_all(sum, na.rm = TRUE) %>% arrange(desc(行业代码))
dt2013 = dt2013 %>% group_by(行业代码) %>% summarise_all(sum, na.rm = TRUE) %>% arrange(desc(行业代码))


dt2004 = dt2004 %>% summarise(行业代码, avg2004 = `从业人数2004` / cou04)
dt2005 = dt2005 %>% summarise(行业代码, avg2005 = `从业人数2005` / cou05)
dt2006 = dt2006 %>% summarise(行业代码, avg2006 = `从业人数2006` / cou06)
dt2007 = dt2007 %>% summarise(行业代码, avg2007 = `从业人数2007` / cou07)
dt2008 = dt2008 %>% summarise(行业代码, avg2008 = `从业人数2008` / cou08)
dt2009 = dt2009 %>% summarise(行业代码, avg2009 = `从业人数2009` / cou09)
dt2010 = dt2010 %>% summarise(行业代码, avg2010 = `从业人数2010` / cou10)
dt2011 = dt2011 %>% summarise(行业代码, avg2011 = `从业人数2011` / cou11)
dt2012 = dt2012 %>% summarise(行业代码, avg2012 = `从业人数2012` / cou12)
dt2013 = dt2013 %>% summarise(行业代码, avg2013 = `从业人数2013` / cou13)
``` 

###

```{r}
table(dt2004$行业代码 %in% dt2004$行业代码)
table(dt2005$行业代码 %in% dt2004$行业代码)
table(dt2006$行业代码 %in% dt2004$行业代码)
table(dt2007$行业代码 %in% dt2004$行业代码)
table(dt2008$行业代码 %in% dt2004$行业代码)
table(dt2009$行业代码 %in% dt2004$行业代码)
table(dt2010$行业代码 %in% dt2004$行业代码)
table(dt2011$行业代码 %in% dt2004$行业代码)
table(dt2012$行业代码 %in% dt2004$行业代码)
table(dt2013$行业代码 %in% dt2004$行业代码)
```

### 2004为基数年

```{r}
dt2004$行业代码 = as.numeric(as.character(dt2004$行业代码))
dt2005$行业代码 = as.numeric(as.character(dt2005$行业代码))
dt2006$行业代码 = as.numeric(as.character(dt2006$行业代码))
dt2007$行业代码 = as.numeric(as.character(dt2007$行业代码))
dt2008$行业代码 = as.numeric(as.character(dt2008$行业代码))
dt2009$行业代码 = as.numeric(as.character(dt2009$行业代码))
dt2010$行业代码 = as.numeric(as.character(dt2010$行业代码))
dt2011$行业代码 = as.numeric(as.character(dt2011$行业代码))
dt2012$行业代码 = as.numeric(as.character(dt2012$行业代码))
dt2013$行业代码 = as.numeric(as.character(dt2013$行业代码))



行业类别名称FL = read_excel("国民经济行业分类与代码(GB-T-4754-2002).xlsx")
行业类别名称FL$行业代码 = as.numeric(行业类别名称FL$行业代码)
all2004 = left_join(dt2004,行业类别名称FL,by = '行业代码')
all2004 = all2004[c(1,3,2)]

all2004 = left_join(all2004, dt2005, by = '行业代码')
all2004 = left_join(all2004, dt2006, by ='行业代码')
all2004 = left_join(all2004, dt2007, by ='行业代码')
all2004 = left_join(all2004, dt2008, by ='行业代码')
all2004 = left_join(all2004, dt2009, by ='行业代码')
all2004 = left_join(all2004, dt2010, by ='行业代码')
all2004 = left_join(all2004, dt2011, by ='行业代码')
all2004 = left_join(all2004, dt2012, by ='行业代码')
all2004 = left_join(all2004, dt2013, by ='行业代码')

all2004 =  na.omit(all2004)




all2004m = as.matrix(all2004)
all2004mt = t(all2004m)
all2004mt = as.data.frame(all2004mt)

index = gather(all2004mt[1,])
index = rep(index$value,each = 10)

all2004mt = all2004mt[-c(1,2),]

oneline2004 = gather(all2004mt)
oneline2004$key = index
oneline2004$year = rep(2004:2013, times = 103)
oneline2004$value = as.numeric(oneline2004$value)

colnames(行业类别名称FL)[1] = 'key'
行业类别名称FL$key = as.character(行业类别名称FL$key)
oneline2004 = left_join(oneline2004, 行业类别名称FL, by = 'key')

```

```{r}
aa = oneline2004[1:40,]%>%
        ggplot(aes(x = year, y = value, color = `行业名称(FirmLevel)`)) +
        geom_point()+
        geom_line()+
        labs(title = 'Company employment change', y = 'Number')
ggplotly(aa)

```

